version: "3.8"
services:
  config-server:
    image: bookstore/configserver:latest
    ports:
      - "8888:8888"
    networks:
      - bookstore-network

  eureka-server:
    image: bookstore/eureka-server:latest
    ports:
      - "8090:8080"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
    networks:
      - bookstore-network

  mail-service:
    image: bookstore/mail-service:latest
    ports:
      - "8885:8885"
    networks:
      - bookstore-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://configserver:8090/

  API-gateway:
    image: bookstore/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://configserver:8090/
    networks:
      - bookstore-network

  books-service-db:
    image: mysql:8.4
    restart: always
    env_file:
      - ./.env
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - bookstore-network
  books-service:
    image: bookstore/books-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://configserver:8090/
    networks:
      - bookstore-network

  users-service:
    image: bookstore/users-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://configserver:8090/
    networks:
      - bookstore-network
  users-service-db:
    image: mysql:8.4
    restart: always
    env_file:
      - ./.env
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - bookstore-network

  orders-service:
    image: bookstore/orders-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://configserver:8090/
    networks:
      - bookstore-network
  orders-service-db:
    image: mysql:8.4
    restart: always
    env_file:
      - ./.env
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - bookstore-network
