spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/orders_service
    password: E15@root
  application:
    name: orders-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: '8083'

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application-config:
  book-service: http://localhost:8080
