server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
    version: v1
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka